[ADD] inventory_adjustment_reason
GlodoUK/stock-delivery pull request #13
Opened 2022-11-24 09:35 UTC by cshardey

2022-12-02 18:04 UTC, theangryangel requested changes

2022-12-02 18:04 UTC, theangryangel commented on inventory_adjustment_reason/models/stock_quant.py
> +    note = fields.Text(string="Inventory Adjustment Reason")
This only stores the note on the stock.quant.

If I make a second adjustment the original note is lost.

Assuming they want to keep the note, this needs to be persisted to the stock.move when the quant is applied.

The new field would also need to be displayed on the stock.move form.

(I've not tested this code).

```suggestion
class StockQuant(models.Model):
    _inherit = "stock.quant"
    note = fields.Text(string="Inventory Adjustment Reason")
    
    def _get_inventory_move_values(self, qty, location_id, location_dest_id, out=False):
        res = super()._get_inventory_move_values(
            qty, location_id, location_dest_id, out=out
        )

        res.update(
            {
                "note": self.note,
            }
        )

        return res

    def _apply_inventory(self):
        res = super()._apply_inventory()

        self.write({"note": False})

        return res

    @api.model
    def _get_inventory_fields_write(self):
        res = super()._get_inventory_fields_write()
        res.append("note")
        return res


class StockMove(models.Model):
    _inherit = "stock.move"

    note = fields.Text()
```

2022-12-22 11:18 UTC, theangryangel requested changes

2022-12-22 11:18 UTC, theangryangel commented on inventory_adjustment_reason/tests/test_inventory_adjustment_note.py
> +        self.assertEqual(stock_adjustment.note, "This is a test note")
Needs a test to check that the resulting `stock.move`'s note field is also set and matches.

2023-01-04 16:10 UTC, BlommaertsEdwin approved these changes

2023-01-26 12:36 UTC, BlommaertsEdwin approved these changes

2023-01-26 12:49 UTC, merged